app = "uniswap"

[build]
image = "registry.fly.io/uniswap"

[http_service]
internal_port = 10000
force_https = true

[http_service.concurrency]
type = "requests"
soft_limit = 200
hard_limit = 250

[[http_service.checks]]
grace_period = "10s"
interval = "30s"
method = "GET"
timeout = "5s"
path = "/healthz"

[[vm]]
size = "shared-cpu-1x"
memory = "2gb"

[env]
CARTESI_BLOCKCHAIN_FINALITY_OFFSET = "1"
CARTESI_BLOCKCHAIN_ID = "11155111"
CARTESI_CONTRACTS_APPLICATION_ADDRESS = "0x13041EF31E5116483CF686a5253298C88892D57c"
CARTESI_CONTRACTS_AUTHORITY_ADDRESS = "0xF7cCAce10D1b1ec09A685f95F22c4D6d4B7f6EE6"
CARTESI_CONTRACTS_HISTORY_ADDRESS = "0x17eDe34EB31bef84448FB9bC50eB25b8Ec9d015b"
CARTESI_CONTRACTS_INPUT_BOX_ADDRESS = "0x59b22D57D4f067708AB0c00552767405926dc768"
CARTESI_CONTRACTS_INPUT_BOX_DEPLOYMENT_BLOCK_NUMBER = "3963384"
CARTESI_EPOCH_LENGTH = "1"